use customer_behaviour;

-- 1. Total revnue generated by male vs female customer
select gender,sum(purchase_amount) from customer
group by gender;

-- 2. which customer used discount but spent more than the avg purchase amount?
select customer_id ,purchase_amount from customer 
where
 discount_applied = "Yes" 
  and 
 purchase_amount > (select avg(purchase_amount) from customer);
 
 -- 3.Which customers purchase most frequently and give high ratings?
 select 
		customer_id,
        previous_purchases,purchase_frequency_days,
        round(review_rating,1) as review_rating,
        case
			when previous_purchases > 10 
            and review_rating >= 4 
            AND purchase_frequency_days < 30 
            then 'high value'
            when previous_purchases > 5 
            AND purchase_frequency_days < 60
            then 'median value'
            else 'low value'
            end as customer_segment
		from customer
        order by previous_purchases desc,review_rating desc,purchase_frequency_days asc;
        
-- 3. Which category has highest avg rating,highest revenue,lowest engagement?
select category,
	   count(*) as total_orders ,
       round(avg(review_rating),2) as avg_rating,
       sum(purchase_amount) as total_amount
from customer
group by category
order by total_amount desc;

-- 4. which are the top 5 products with highest avg review rating?
select  item_purchased as product,
        round(avg(review_rating),2) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;
 
 -- 5.Compare the average purchase amount between standard and express shipping?
 select shipping_type,round(avg(purchase_amount),2) as avg_purchase_amount 
 from customer
 where shipping_type in ('Standard','Express')
 group by shipping_type;

-- 6. Do subsriber customers spends more? compare avg spent and total revenue between subscribers and non-subscribers.
select subscription_status,
	   count(customer_id) as total_customers,
       round(avg(purchase_amount),2) as avg_spend,
       round(sum(purchase_amount),2) as total_spend
from customer
group by subscription_status;

-- 7.Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
       round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_applied_rate
from customer
group by item_purchased
order by discount_applied_rate desc
limit 5;
 
 -- 8.Segment customer based on their total number of purchase,show the total customers of each segment.
 with customer_type as(
      select customer_id,previous_purchases,
      case
          when previous_purchases = 1 then 'new'
          when previous_purchases between 2 and 15 then 'returninhg'
          else 'loyal'
		  end as customer_segment
	 from customer)
select customer_segment,count(*) as total_customers 
from customer_type
group by customer_segment
order by total_customers desc;
	
-- 9.Which frequency group contributes most customers?based on frequency_of_purchases
select frequency_of_purchases as customer_group,count(*) as total_customers
from customer
group by frequency_of_purchases
order by total_customers desc;

-- 10. What are the top 3 most purchase product within each category?
with item_count as (
    select category,item_purchased,
           count(*) as total_orders,
           row_number() over(partition by category order by count(*) desc) as product_rank
	from customer
    group by category,item_purchased)
 
select * from item_count
where product_rank <= 3;

-- 11. What are the top 3 product based on avg rating within each category?
with rating_rank as(
	select category,item_purchased,
		   round(avg(review_rating),2) as avg_rating,
		   rank() over(partition by category order by avg(review_rating) desc) as item_rank
	from customer
	group by category,item_purchased
    )
select * from rating_rank
where item_rank <= 3;
-- 12. Are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- 13. season wise Top 3 product by Revenue ?
with season_products as(
		select season,item_purchased,
			   sum(purchase_amount) as total_revenue,
			   row_number() over(partition by season order by sum(purchase_amount) desc) as item_rank
		from customer
		group by season,item_purchased
       )
       
select * from season_products
where item_rank <= 3 ;
    
-- 14.What is revenue genaraed by age group and also by gender?
select gender,age_group,
	   sum(purchase_amount) as revenue,
       round(100 * sum(purchase_amount)/(select sum(purchase_amount) from customer),2) as revenue_percentage
from customer
group by gender,age_group
order by age_group,revenue desc;

 